Fix upgrade-aws action
This fixes the failing upgrade-aws action.

Currently failing with:

```
$ /home/runner/work/pulumi-awsx/pulumi-awsx/sdk/nodejs/node_modules/.bin/tsc
node_modules/@smithy/core/dist-types/submodules/cbor/cbor.d.ts(13,28): error TS2315: Type 'Uint8Array' is not generic.
```

Looks like the @aws-sdk/aws-ecs dependency installs @smithy/core which
now requires typescript@^5.7.0 [see this issue](https://github.com/smithy-lang/smithy-typescript/issues/1675)

I also ran the upgrade steps manually.

fixes #1692, fixes #1615