Fix build break
Build was failing with:

```
cloudwatch/metric.ts:333:16 - error TS2339: Property 'hasOwnProperty' does not exist on type 'T'.
333     return obj.hasOwnProperty(key);
```